#!/bash/bash
REPO="stepango/kokoko"
MAIN_BRANCH="main"

PROJECT_OWNER="stepango"
PROJECT_NUMBER="2"

STATUS_FIELD_NAME="Status"
TODO_VALUE="Ready"
IN_PROGRESS_VALUE="In progress"
DONE_VALUE="Done"
BACKLOG_VALUE="Backlog"

PRIORITY_FIELD_NAME="Priority"
PRIORITY_MODE="single_select"   # or number
PRIORITY_ORDER="P0,P1,P2,P3"

LOOP_INTERVAL_SECS="20"

COMMENT_PREFIX="@:robot:"

MAX_PARALLEL_COMMENT_JOBS="4"
MAX_PARALLEL_PR_JOBS="2"
ISSUE_EXECUTION_CONCURRENCY="1"

CONFLICT_STRATEGY="rebase"      # or merge

TEST_COMMAND="./scripts/test.sh"
BUILD_COMMAND="./scripts/build.sh"

BOT_GIT_NAME="robot"
BOT_GIT_EMAIL="robot@example.com"

GEMINI_MODEL=""
GEMINI_ARGS=""

ENABLE_AUTO_PUSH="true"
ENABLE_PROJECT_STATUS_UPDATES="true"
ENABLE_PR_COMMENTS="true"
ENABLE_ISSUE_COMMENTS="true"

KEEP_FAILED_WORKTREES="false"
ALLOW_ISSUE_REFUSAL="true"
REFUSAL_REQUIRES_BACKLOG_MOVE="true"
